In [36]:
import numpy as np
import pandas as pd
import glob
import os

In [39]:
l = [pd.read_csv(filename, header = 0) for filename in glob.glob("/mnt/c/Users/umar_/Documents/Projects/Data/NBA/Through 15 games/*.csv")]

,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
0,1,1,2003-10-29,18-303,CLE,@,SAC,L (-14),1,42:00,...,4,6,9,4,0,2,3,25,24.7,-9
1,2,2,2003-10-30,18-304,CLE,@,PHO,L (-9),1,41:00,...,10,12,8,1,0,7,1,21,14.7,-3
2,3,3,2003-11-01,18-306,CLE,@,POR,L (-19),1,39:00,...,4,4,6,2,0,2,3,8,5.0,-21
3,4,4,2003-11-05,18-310,CLE,NaN,DEN,L (-4),1,41:00,...,9,11,7,2,3,2,1,7,11.2,-3
4,5,5,2003-11-07,18-312,CLE,@,IND,L (-1),1,44:00,...,5,5,3,0,0,7,2,23,9.0,-7
5,6,6,2003-11-08,18-313,CLE,NaN,WAS,W (+13),1,45:00,...,3,8,9,1,1,2,1,17,15.7,14
6,7,7,2003-11-10,18-315,CLE,NaN,NYK,W (+14),1,34:00,...,4,5,4,1,1,2,0,17,15.8,20
7,8,8,2003-11-12,18-317,CLE,@,MIA,L (-5),1,42:00,...,2,3,7,2,1,4,3,18,12.8,-4
8,9,9,2003-11-14,18-319,CLE,@,BOS,L (-9),1,35:00,...,4,5,3,0,0,4,3,10,0.8,-1
9,10,10,2003-11-15,18-320,CLE,NaN,PHI,W (+3),1,47:00,...,5,5,8,1,2,5,2,22,15.6,8
10,11,11,2003-11-18,18-323,CLE,NaN,LAC,W (+8),1,39:00,...,5,7,8,0,1,3,2,14,9.8,1
11,12,12,2003-11-19,18-324,CLE,@,WAS,L (-11),1,40:00,...,5,7,8,2,1,4,2,28,25.0,-5
12,13,13,2003-11-21,18-326,CLE,NaN,MIN,L (-14),1,36:00,...,7,9,2,1,0,1,4,19,12.2,-5
13,14,14,2003-11-22,18-327,CLE,@,ATL,L (-9),1,42:00,...,4,6,4,2,1,3,1,15,9.3,-6
14,15,15,2003-11-26,18-331,CLE,@,NOH,L (-10),1,39:00,...,6,8,9,0,0,4,1,15,10.2,-13
15,16,16,2003-11-28,18-333,CLE,@,DET,L (-4),1,36:00,...,2,2,7,0,0,4,3,6,1.1,-10
16,17,17,2003-11-29,18-334,CLE,NaN,MEM,L (-7),1,55:00,...,14,16,7,1,1,8,1,33,22.4,-10
17,18,18,2003-12-02,18-337,CLE,@,DEN,L (-12),1,32:00,...,3,6,5,2,0,2,4,19,12.2,-12
18,19,19,2003-12-03,18-338,CLE,@,LAC,L (-10),1,34:00,...,2,6,8,2,0,5,2,4,0.9,3
19,20,20,2003-12-06,18-341,CLE,NaN,ATL,W (+10),1,36:00,...,5,6,5,2,1,3,2,8,5.8,-5
20,21,21,2003-12-09,18-344,CLE,NaN,TOR,L (-7),1,37:00,...,5,5,3,1,0,2,2,18,11.4,-2
21,22,22,2003-12-11,18-346,CLE,NaN,DET,W (+9),1,43:00,...,2,3,9,1,1,4,3,23,14.8,9
22,23,23,2003-12-13,18-348,CLE,NaN,BOS,L (-7),1,45:00,...,2,3,4,0,0,2,2,37,27.5,-2
23,24,24,2003-12-15,18-350,CLE,@,IND,L (-10),1,44:00,...,3,4,6,3,3,6,1,27,23.9,-12
24,25,25,2003-12-17,18-352,CLE,NaN,HOU,L (-4),1,36:00,...,1,1,3,0,0,2,2,17,5.7,-9
25,26,26,2003-12-19,18-354,CLE,@,PHI,W (+7),1,42:00,...,3,4,5,4,0,4,1,36,29.5,9
26,27,27,2003-12-20,18-355,CLE,@,CHI,W (+8),1,42:00,...,5,6,10,2,2,4,2,32,28.0,9
27,28,28,2003-12-23,18-358,CLE,NaN,NOH,W (+11),1,39:00,...,4,6,2,6,1,5,1,22,14.3,9
28,29,29,2003-12-25,18-360,CLE,@,ORL,L (-12),1,47:00,...,1,2,6,2,1,8,0,34,19.1,-9
29,30,30,2003-12-26,18-361,CLE,NaN,CHI,L (-7),1,34:00,...,2,3,4,1,2,5,0,18,5.1,-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,50,50,2004-02-11,19-043,CLE,NaN,NJN,L (-20),1,29:00,...,1,2,5,1,0,5,0,9,1.2,-12
50,51,51,2004-02-18,19-050,CLE,NaN,DAL,L (-16),1,34:00,...,2,4,9,0,1,5,2,16,13.2,-15
51,52,52,2004-02-20,19-052,CLE,NaN,SAS,W (+2),1,39:00,...,9,11,2,2,1,2,0,32,27.7,3
52,53,53,2004-02-22,19-054,CLE,@,NYK,W (+6),1,44:00,...,4,5,3,1,0,1,2,22,12.4,11
53,54,54,2004-02-23,19-055,CLE,NaN,NOH,W (+4),1,36:00,...,4,4,6,2,5,1,3,21,21.3,4
54,55,55,2004-02-25,19-057,CLE,@,HOU,L (-6),1,39:00,...,5,7,5,2,1,2,1,11,6.3,-5
55,56,56,2004-02-27,19-059,CLE,@,ORL,W (+5),1,49:00,...,10,11,3,3,1,5,1,30,24.8,7
56,57,57,2004-03-01,19-062,CLE,@,CHI,L (-11),1,41:00,...,3,3,3,4,1,3,2,18,12.0,-4
57,58,58,2004-03-03,19-064,CLE,NaN,ATL,W (+32),1,28:00,...,6,7,3,1,1,1,0,24,20.6,22
58,59,59,2004-03-05,19-066,CLE,@,NOH,W (+3),1,37:00,...,4,6,4,2,0,4,5,19,10.9,1
59,60,60,2004-03-06,19-067,CLE,NaN,MIL,W (+9),1,43:00,...,5,7,10,4,1,2,3,24,22.6,9
60,61,61,2004-03-08,19-069,CLE,@,ATL,W (+6),1,45:00,...,4,6,7,1,0,2,1,34,27.6,11
61,62,62,2004-03-10,19-071,CLE,@,TOR,W (+14),1,34:00,...,2,3,4,1,0,2,2,14,8.4,16
62,63,63,2004-03-14,19-075,CLE,NaN,IND,W (+3),1,44:00,...,3,3,4,3,1,4,3,26,16.8,5
63,64,64,2004-03-16,19-077,CLE,NaN,CHI,W (+24),1,32:00,...,2,5,8,0,5,4,1,17,14.0,24
64,65,65,2004-03-19,19-080,CLE,NaN,UTA,L (-9),1,33:00,...,0,0,7,2,1,2,3,14,8.6,-2
65,66,66,2004-03-21,19-082,CLE,NaN,DET,L (-20),1,36:00,...,5,7,3,0,2,4,4,15,5.5,-21
66,67,67,2004-03-23,19-084,CLE,NaN,PHO,L (-17),1,42:00,...,1,2,6,3,1,5,0,25,16.6,-12
67,68,68,2004-03-26,19-087,CLE,@,PHI,L (-15),1,33:00,...,1,3,7,0,1,5,1,16,9.2,-24
68,69,69,2004-03-27,19-088,CLE,NaN,NJN,W (+3),1,43:00,...,4,6,13,3,0,2,1,41,39.0,10
69,70,70,2004-03-29,19-090,CLE,@,SAS,L (-8),1,32:00,...,2,2,4,0,1,2,0,18,9.7,-14
70,71,71,2004-03-30,19-091,CLE,@,DAL,L (-17),1,42:00,...,4,5,6,4,0,3,2,28,23.3,-10
71,72,72,2004-04-02,19-094,CLE,@,MIL,L (-18),1,36:00,...,7,7,7,5,0,5,3,20,16.1,-13
72,73,73,2004-04-03,19-095,CLE,NaN,GSW,L (-3),1,46:00,...,5,8,10,1,1,3,1,34,26.5,-3
73,74,74,2004-04-06,19-098,CLE,NaN,TOR,L (-1),1,46:00,...,5,6,4,3,0,3,2,21,14.1,2
74,75,75,2004-04-07,19-099,CLE,@,MEM,L (-18),1,36:00,...,3,3,5,3,0,2,4,14,11.3,-11
75,76,76,2004-04-09,19-101,CLE,@,MIA,L (-15),1,42:00,...,6,7,8,1,0,8,2,24,15.3,-16
76,77,77,2004-04-10,19-102,CLE,NaN,MIA,W (+11),1,32:00,...,2,3,11,0,0,2,3,10,8.5,14
77,78,78,2004-04-12,19-104,CLE,NaN,MIL,W (+4),1,45:00,...,6,7,9,2,0,1,1,27,24.8,11
78,79,79,2004-04-14,19-106,CLE,@,NYK,W (+10),1,35:00,...,1,1,5,3,0,5,1,17,9.7,-6

[    Rk   G        Date     Age   Tm Unnamed: 5  Opp Unnamed: 7  GS     MP  \
 0    1   1  2003-10-29  18-303  CLE          @  SAC    L (-14)   1  42:00
 1    2   2  2003-10-30  18-304  CLE          @  PHO     L (-9)   1  41:00
 2    3   3  2003-11-01  18-306  CLE          @  POR    L (-19)   1  39:00
 3    4   4  2003-11-05  18-310  CLE        NaN  DEN     L (-4)   1  41:00
 4    5   5  2003-11-07  18-312  CLE          @  IND     L (-1)   1  44:00
 5    6   6  2003-11-08  18-313  CLE        NaN  WAS    W (+13)   1  45:00
 6    7   7  2003-11-10  18-315  CLE        NaN  NYK    W (+14)   1  34:00
 7    8   8  2003-11-12  18-317  CLE          @  MIA     L (-5)   1  42:00
 8    9   9  2003-11-14  18-319  CLE          @  BOS     L (-9)   1  35:00
 9   10  10  2003-11-15  18-320  CLE        NaN  PHI     W (+3)   1  47:00
 10  11  11  2003-11-18  18-323  CLE        NaN  LAC     W (+8)   1  39:00
 11  12  12  2003-11-19  18-324  CLE          @  WAS    L (-11)   1  40:00
 12  13  13  2003-11-21  18-326  CLE        NaN  MIN    L (-14)   1  36:00
 13  14  14  2003-11-22  18-327  CLE          @  ATL     L (-9)   1  42:00
 14  15  15  2003-11-26  18-331  CLE          @  NOH    L (-10)   1  39:00
 15  16  16  2003-11-28  18-333  CLE          @  DET     L (-4)   1  36:00
 16  17  17  2003-11-29  18-334  CLE        NaN  MEM     L (-7)   1  55:00
 17  18  18  2003-12-02  18-337  CLE          @  DEN    L (-12)   1  32:00
 18  19  19  2003-12-03  18-338  CLE          @  LAC    L (-10)   1  34:00
 19  20  20  2003-12-06  18-341  CLE        NaN  ATL    W (+10)   1  36:00
 20  21  21  2003-12-09  18-344  CLE        NaN  TOR     L (-7)   1  37:00
 21  22  22  2003-12-11  18-346  CLE        NaN  DET     W (+9)   1  43:00
 22  23  23  2003-12-13  18-348  CLE        NaN  BOS     L (-7)   1  45:00
 23  24  24  2003-12-15  18-350  CLE          @  IND    L (-10)   1  44:00
 24  25  25  2003-12-17  18-352  CLE        NaN  HOU     L (-4)   1  36:00
 25  26  26  2003-12-19  18-354  CLE          @  PHI     W (+7)   1  42:00
 26  27  27  2003-12-20  18-355  CLE          @  CHI     W (+8)   1  42:00
 27  28  28  2003-12-23  18-358  CLE        NaN  NOH    W (+11)   1  39:00
 28  29  29  2003-12-25  18-360  CLE          @  ORL    L (-12)   1  47:00
 29  30  30  2003-12-26  18-361  CLE        NaN  CHI     L (-7)   1  34:00
 ..  ..  ..         ...     ...  ...        ...  ...        ...  ..    ...
 49  50  50  2004-02-11  19-043  CLE        NaN  NJN    L (-20)   1  29:00
 50  51  51  2004-02-18  19-050  CLE        NaN  DAL    L (-16)   1  34:00
 51  52  52  2004-02-20  19-052  CLE        NaN  SAS     W (+2)   1  39:00
 52  53  53  2004-02-22  19-054  CLE          @  NYK     W (+6)   1  44:00
 53  54  54  2004-02-23  19-055  CLE        NaN  NOH     W (+4)   1  36:00
 54  55  55  2004-02-25  19-057  CLE          @  HOU     L (-6)   1  39:00
 55  56  56  2004-02-27  19-059  CLE          @  ORL     W (+5)   1  49:00
 56  57  57  2004-03-01  19-062  CLE          @  CHI    L (-11)   1  41:00
 57  58  58  2004-03-03  19-064  CLE        NaN  ATL    W (+32)   1  28:00
 58  59  59  2004-03-05  19-066  CLE          @  NOH     W (+3)   1  37:00
 59  60  60  2004-03-06  19-067  CLE        NaN  MIL     W (+9)   1  43:00
 60  61  61  2004-03-08  19-069  CLE          @  ATL     W (+6)   1  45:00
 61  62  62  2004-03-10  19-071  CLE          @  TOR    W (+14)   1  34:00
 62  63  63  2004-03-14  19-075  CLE        NaN  IND     W (+3)   1  44:00
 63  64  64  2004-03-16  19-077  CLE        NaN  CHI    W (+24)   1  32:00
 64  65  65  2004-03-19  19-080  CLE        NaN  UTA     L (-9)   1  33:00
 65  66  66  2004-03-21  19-082  CLE        NaN  DET    L (-20)   1  36:00
 66  67  67  2004-03-23  19-084  CLE        NaN  PHO    L (-17)   1  42:00
 67  68  68  2004-03-26  19-087  CLE          @  PHI    L (-15)   1  33:00
 68  69  69  2004-03-27  19-088  CLE        NaN  NJN     W (+3)   1  43:00
 69  70  70  2004-03-29  19-090  CLE          @  SAS     L (-8)   1  32:00
 70  71  71  2004-03-30  19-091  CLE          @  DAL    L (-17)   1  42:00
 71  72  72  2004-04-02  19-094  CLE          @  MIL    L (-18)   1  36:00
 72  73  73  2004-04-03  19-095  CLE        NaN  GSW     L (-3)   1  46:00
 73  74  74  2004-04-06  19-098  CLE        NaN  TOR     L (-1)   1  46:00
 74  75  75  2004-04-07  19-099  CLE          @  MEM    L (-18)   1  36:00
 75  76  76  2004-04-09  19-101  CLE          @  MIA    L (-15)   1  42:00
 76  77  77  2004-04-10  19-102  CLE        NaN  MIA    W (+11)   1  32:00
 77  78  78  2004-04-12  19-104  CLE        NaN  MIL     W (+4)   1  45:00
 78  79  79  2004-04-14  19-106  CLE          @  NYK    W (+10)   1  35:00

    ...   DRB  TRB  AST  STL  BLK  TOV  PF  PTS  GmSc  +/-
 0  ...     4    6    9    4    0    2   3   25  24.7   -9
 1  ...    10   12    8    1    0    7   1   21  14.7   -3
 2  ...     4    4    6    2    0    2   3    8   5.0  -21
 3  ...     9   11    7    2    3    2   1    7  11.2   -3
 4  ...     5    5    3    0    0    7   2   23   9.0   -7
 5  ...     3    8    9    1    1    2   1   17  15.7   14
 6  ...     4    5    4    1    1    2   0   17  15.8   20
 7  ...     2    3    7    2    1    4   3   18  12.8   -4
 8  ...     4    5    3    0    0    4   3   10   0.8   -1
 9  ...     5    5    8    1    2    5   2   22  15.6    8
 10 ...     5    7    8    0    1    3   2   14   9.8    1
 11 ...     5    7    8    2    1    4   2   28  25.0   -5
 12 ...     7    9    2    1    0    1   4   19  12.2   -5
 13 ...     4    6    4    2    1    3   1   15   9.3   -6
 14 ...     6    8    9    0    0    4   1   15  10.2  -13
 15 ...     2    2    7    0    0    4   3    6   1.1  -10
 16 ...    14   16    7    1    1    8   1   33  22.4  -10
 17 ...     3    6    5    2    0    2   4   19  12.2  -12
 18 ...     2    6    8    2    0    5   2    4   0.9    3
 19 ...     5    6    5    2    1    3   2    8   5.8   -5
 20 ...     5    5    3    1    0    2   2   18  11.4   -2
 21 ...     2    3    9    1    1    4   3   23  14.8    9
 22 ...     2    3    4    0    0    2   2   37  27.5   -2
 23 ...     3    4    6    3    3    6   1   27  23.9  -12
 24 ...     1    1    3    0    0    2   2   17   5.7   -9
 25 ...     3    4    5    4    0    4   1   36  29.5    9
 26 ...     5    6   10    2    2    4   2   32  28.0    9
 27 ...     4    6    2    6    1    5   1   22  14.3    9
 28 ...     1    2    6    2    1    8   0   34  19.1   -9
 29 ...     2    3    4    1    2    5   0   18   5.1  -12
 .. ...   ...  ...  ...  ...  ...  ...  ..  ...   ...  ...
 49 ...     1    2    5    1    0    5   0    9   1.2  -12
 50 ...     2    4    9    0    1    5   2   16  13.2  -15
 51 ...     9   11    2    2    1    2   0   32  27.7    3
 52 ...     4    5    3    1    0    1   2   22  12.4   11
 53 ...     4    4    6    2    5    1   3   21  21.3    4
 54 ...     5    7    5    2    1    2   1   11   6.3   -5
 55 ...    10   11    3    3    1    5   1   30  24.8    7
 56 ...     3    3    3    4    1    3   2   18  12.0   -4
 57 ...     6    7    3    1    1    1   0   24  20.6   22
 58 ...     4    6    4    2    0    4   5   19  10.9    1
 59 ...     5    7   10    4    1    2   3   24  22.6    9
 60 ...     4    6    7    1    0    2   1   34  27.6   11
 61 ...     2    3    4    1    0    2   2   14   8.4   16
 62 ...     3    3    4    3    1    4   3   26  16.8    5
 63 ...     2    5    8    0    5    4   1   17  14.0   24
 64 ...     0    0    7    2    1    2   3   14   8.6   -2
 65 ...     5    7    3    0    2    4   4   15   5.5  -21
 66 ...     1    2    6    3    1    5   0   25  16.6  -12
 67 ...     1    3    7    0    1    5   1   16   9.2  -24
 68 ...     4    6   13    3    0    2   1   41  39.0   10
 69 ...     2    2    4    0    1    2   0   18   9.7  -14
 70 ...     4    5    6    4    0    3   2   28  23.3  -10
 71 ...     7    7    7    5    0    5   3   20  16.1  -13
 72 ...     5    8   10    1    1    3   1   34  26.5   -3
 73 ...     5    6    4    3    0    3   2   21  14.1    2
 74 ...     3    3    5    3    0    2   4   14  11.3  -11
 75 ...     6    7    8    1    0    8   2   24  15.3  -16
 76 ...     2    3   11    0    0    2   3   10   8.5   14
 77 ...     6    7    9    2    0    1   1   27  24.8   11
 78 ...     1    1    5    3    0    5   1   17   9.7   -6

 [79 rows x 30 columns]]